### ISSUE TITLE
Any schedule to convert to Notion official API?

### ISSUE THREAD

**Issue by YUX** [craigary/nobelium#128]
**Is your feature request related to a problem? Please describe.**
- Well the notion public beta API is released for days, the token hack is less secure than notion official solution.

**Describe the solution you'd like**
- Use notion API, and *nobelium* is a perfect use case for that
    - per https://developers.notion.com/

**Describe alternatives you've considered**

- Wait until the formal release API

**Additional context**

**Comment by craigary** [comment]
Hi, Nobelium will not switch to official API anytime soon, since currently the API is still in beta and lack a tons of features.

For example, there're tons of types of blocks are missing, we don't have a good package to render the block to html easily, and we ain't able to access the full width status, etc.
