### ISSUE TITLE
New posts don't show up

### ISSUE THREAD

**Issue by Holaeric** [craigary/nobelium#229]
**Bug Description:**
New posts don't show up properly related with timezone.

**To Reproduce**
Set timezone to GMT+8 and add a new post in the Notion database linked with Nobelium at 0:00.

**Expected behavior**
Page don't show on the Nobelium generated site immediately but will show 8 hrs later.

**Platform:**

- OS: Windows
- Browser: Chrome
- Version: 99.0.4844.51

**Comment by 1muggle** [comment]
Hi @CryZJ , you mention "Set timezone to GMT+8", which exactly is that set in? Is it in your OS or in the database properties of your Notion or somewhere else?

> **Bug Description:** New posts don't show up properly related with timezone.
> 
> **To Reproduce** Set timezone to GMT+8 and add a new post in the Notion database linked with Nobelium at 0:00.
> 
> **Expected behavior** Page don't show on the Nobelium generated site immediately but will show 8 hrs later.
> 
> **Platform:**
> 
> * OS: Windows
> * Browser: Chrome
> * Version: 99.0.4844.51

**Comment by CryZJ** [comment]
The timezone config of Notion is synced with OS by default. The timezone of my OS was set as UTC+8. The problem is that Nobelium won't show posts which date is beyond "today", so when I made a new post at 0:00 today(UTC+8), Nobelium would consider that current time is actually 16:00 yesterday (UTC+0) and doesn't publish the post.

**Comment by SilentDepth** [comment]
As a temporary workaround, you can set a `TZ` environment variable on Vercel to `Asia/Shanghai` and redeploy your blog. You can find the redeploy button on the “Deployments” page of your Vercel project.

**Comment by SilentDepth** [comment]
@BeautyyuYanli 
Well, that was unexpected. Yes, it is intended to hide _future posts_. Say some users might want to publish posts at a specific time, i.e. scheduled publishing. At the moment you might have to set a past `date`. We’ll fix this issue as soon as we found a solid solution.

**Comment by SilentDepth** [comment]
@BeautyyuYanli 
You are right. That’s why you need to set the `TZ` environment variable, to add the missing timezone info for Notion. However, it still works most of the time if you schedule publishing on a date level (instead of a time level). Since Vercel doesn’t allow setting `TZ`, we might provide a local config to set the timezone.
