### ISSUE TITLE
Characters are not in serif after setting it in config file

### ISSUE THREAD

**Issue by ice-Yaya** [craigary/nobelium#299]
## Description of the bug
- Chinese characters are not in serif 
    - in post list view: title and summary (Arc, Edge)
    - in individual post: title, tag and content (Arc, Edge)
    - in individual post: content (Safari)
- English characters are not in serif in post content (Arc, Edge, Safari)

## Expected behavior
Both CHN and ENG characters should display in serif

## Reproduction
1. Type both CHN & ENG characters in title, summary, tag and post content
2. Publish the post
3. Use different browsers to check

## Screenshots
↓ Refer to orange arrows for behaviours in Arc and Edge

![CleanShot 2023-03-28 at 22 58 32@2x](https://user-images.githubusercontent.com/73091684/228280516-6263952f-a280-44f6-b461-9b02b50de26a.png)

![CleanShot 2023-03-28 at 21 37 53@2x](https://user-images.githubusercontent.com/73091684/228255899-e6b9c6bf-60ef-45bb-8bd1-d556812c1911.png)

↓ Refer to blue arrows for behaviours in Safari

![CleanShot 2023-03-28 at 23 00 31@2x](https://user-images.githubusercontent.com/73091684/228281008-d8b7645b-be9f-4afd-9f2e-5e536dad651d.png)

## Additional context
Nil

## Software versions

  
- OS: Ventura 13.3
  
- Browser: 
    - Arc: Version 0.95.1 (37921)
    - Edge: Version 0.95.1 (37921)
    - Safari: Version 16.4 (18615.1.26.11.22)
  
- Nobelium: [e8c95a2](https://github.com/ice-Yaya/nobelium/commit/e8c95a22d22fae5f60d32f0de01b2ded34525d90)

**Comment by SilentDepth** [comment]
The font family (serif or sans-serif) of the post content should now follow the config.

However I cannot find a solid solution to handle CJK fonts when you are not using the corresponding site language. It’s difficult to handle such cases due to the complexity of the CJK font world. For now I’ll just keep the current behavior (let your system decide the font). Wish one day we’ll have a better fix.
